# 配置文件版本，请勿修改
version: "1.0.0"

# 繁殖系统配置
breeding:
  # 最低等级要求
  min-level: 5
  
  # 基础繁殖时间（秒）
  # 最短1秒，最长72小时（259200秒）
  base-duration: 300
  
  # 是否使用标题显示提示
  use-title: true
  
  # 经济系统
  economy:
    # 是否启用付费繁殖，false为免费繁殖
    enabled: true
    # 繁殖费用
    breeding-cost: 1000.0
  
  # IV提升配置
  iv-boost:
    # 基础提升系数（0.0-1.0）
    base: 0.1
    # 最大提升系数（0.0-1.0）
    max: 0.5
    # 是否可叠加
    stackable: true
  
  # 闪光概率提升配置
  shiny-boost:
    # 基础提升系数（0.0-1.0）
    base: 0.1
    # 最大提升系数（0.0-1.0）
    max: 0.5
    # 是否可叠加
    stackable: false
  
  # 随机提升配置
  random-boost:
    # 最小提升值
    min: 1
    # 最大提升值
    max: 3
  
  # 高个体值成功率配置
  success-rates:
    # 个体值为28时的成功率
    "28": 0.8
    # 个体值为29时的成功率
    "29": 0.6
    # 个体值为30时的成功率
    "30": 0.4 